FROM python:3.11.15-slim


# Setup a working directory that container will run from
WORKDIR /app

# Copy over any required files from your host
COPY requirements.txt .

# Install the requirements
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["./entrypoint.sh"]
